### ISSUE TITLE
UTF8 下乱码

### ISSUE THREAD

**Issue by zuohuadong** [VirtualHotBar/HotPEToolBox#11]
希望能够兼容

![image](https://user-images.githubusercontent.com/11203929/212845154-4019a865-8eea-4e25-9ad1-855702697074.png)

![image](https://user-images.githubusercontent.com/11203929/212845226-29c510c5-0866-4477-a839-b33a45f9afa2.png)

![image](https://user-images.githubusercontent.com/11203929/212845258-ced11303-9dac-48c3-9b89-2e2db9472dcf.png)

**Comment by VirtualHotBar** [comment]
请尝试https://github.com/VirtualHotBar/HotPE_Client

**Comment by VirtualHotBar** [comment]
已解决，新版客户端已发布

**Comment by NoverNobida** [comment]
@VirtualHotBar 新的客户端发布了，请问什么时候开源新版本？
