### ISSUE TITLE
使用u盘制作启动盘的时候出现的问题

### ISSUE THREAD

**Issue by fengbo1029** [VirtualHotBar/HotPEToolBox#14]
大佬我使用U盘制作hotpe启动盘的时候 提示失败 ，而且会提示安装分区  我点击了没有任何反应
![image](https://user-images.githubusercontent.com/99636954/227412266-a30b12f5-e980-42fb-bb34-984ca8687cef.png)

**Comment by VirtualHotBar** [comment]
换U盘试试或生成iso文件用其他工具写入

**Comment by chaofanx** [comment]
我也是这个问题，昨天新买的u盘
