### ISSUE TITLE
每次启动后1分钟以内蓝屏

### ISSUE THREAD

**Issue by liurunling2009** [VirtualHotBar/HotPEToolBox#16]
蓝屏故障：PAGE_FAULT_IN_NONPAGED_AREA
问题文件：netwsw04.sys
可能是自带的无线网卡驱动文件有问题？（在没有无线网卡的机型上貌似正常，且在蓝屏机器原本的win10系统中一切正常）

**Comment by VirtualHotBar** [comment]
尝试新版
