### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by NoverNobida** [VirtualHotBar/HotPEToolBox#18]
可能由于删除了某些注册表的原因，当前脚本构建出的pe，某些软件会出现中文乱码的现象，例如自带的搜狗输入法，点击双拼那里出现的界面就是乱码的，还有[Clash](https://github.com/Fndroid/clash_for_windows_pkg)的配置文件直接无法载入配置文件而导致无法启动，这两个在其他PE上没有出现。
![2023-07-03_23-04-46](https://github.com/VirtualHotBar/HotPEToolBox/assets/46912250/00521525-4d0e-4fdb-9bf7-b65ca6f24ddb)
![2023-07-03_23-06-14](https://github.com/VirtualHotBar/HotPEToolBox/assets/46912250/82b30e35-5e6d-435c-92d9-a4f3b8405b95)

另外请教一下，从官网下载的版本，和自己构建的版本（基于windows 11 22000.258)，为什么样子完全不一样？

![2023-07-03_23-07-54](https://github.com/VirtualHotBar/HotPEToolBox/assets/46912250/1de87bf1-2027-40af-8b8c-b366ba56a33c)

**Comment by VirtualHotBar** [comment]
目前开源的是2.4版本的构建脚本

**Comment by VirtualHotBar** [comment]
乱码大概是缺字体，在后面的版本中会尝试修复

**Comment by NoverNobida** [comment]
请问2.5版本有计划更新开源吗？

**Comment by VirtualHotBar** [comment]
暂时不公开

**Comment by NoverNobida** [comment]
目前测试应该是删除了某些文件导致乱码，我将
https://github.com/VirtualHotBar/HotPEToolBox/blob/2ec4e9fe3a4cad2f16edca37099354c6da088dc8/main.PY#L87-L107
这几行注释掉，保留这些文件之后，所有都正常了。
