### ISSUE TITLE
如何整合显卡驱动到pe中？

### ISSUE THREAD

**Issue by Matt-wzy** [VirtualHotBar/HotPEToolBox#2]
您好开发者，我简单看了一下您发布的pe工具，确实牛。通过官网的介绍我感觉你已经把pe做成带有pe功能的win to go了。
但是我有一点小疑惑没有解决，就是如何整合驱动程序到镜像或者插件包中？
因为我所使用的笔记本r9000p，其所使用的无线网卡为mt7921，显卡为gtx3060，目前我遇上的问题是无线网卡无法显示wifi（应该是没驱动造成的），屏幕无法调节显示亮度。鉴于您的wiki上没有撰写如何将镜像中没有的脚本整合到镜像中，故前来提问。
期待您的回答。

**Comment by VirtualHotBar** [comment]
可以尝试 添加自定义驱动，打包成HotPE模块：https://wiki.hotpe.top/#/course/driver_hpm
但是没有测试添加显卡驱动

用设备管理器手动安装显卡驱动是可以的！
![image](https://user-images.githubusercontent.com/96966978/168405559-127acae3-8912-4f58-92a8-02e4463acda9.png)
![image](https://user-images.githubusercontent.com/96966978/168405573-d5ce5f84-a5c7-410f-bafc-67c31a3b16d9.png)
![image](https://user-images.githubusercontent.com/96966978/168405535-cae703e7-2b79-46e4-badc-29eee67da91f.png)

**Comment by VirtualHotBar** [comment]
最新版已可一键安装显卡驱动
