### ISSUE TITLE
HOTPE Client安装到系统不能选择安装位置？

### ISSUE THREAD

**Issue by lialonex** [VirtualHotBar/HotPEToolBox#24]
今天正好项选个好用无捆绑的PE，试了下这个还不错，只是有一点，hotpe client版本，安装到 系统的时候，不能选择安装位置，默认是在C:\,如果我想重装系统的话，格式化C:，是不是就不能引导到PE下面，希望能够提供选择安装位置的选项

**Comment by totoro52** [comment]
有的， 我今天刚安装 右下角又得选盘符的，更新到最新版

**Comment by lialonex** [comment]
怎么回事，我的升级最新也也没有选项呢发自我的手机-------- 原始邮件 --------发件人： 龍貓 ***@***.***>日期： 2023年8月20日周日 傍晚5:48收件人： VirtualHotBar/HotPEToolBox ***@***.***>抄送： lialonex ***@***.***>, Author ***@***.***>主    题： Re: [VirtualHotBar/HotPEToolBox] HOTPE Client安装到系统不能选择安装位置？ (Issue #24)
有的， 我今天刚安装 右下角又得选盘符的，更新到最新版

**Comment by awaitla** [comment]
用旧版安装器
