### ISSUE TITLE
发布版运行时会被杀毒软件拦截

### ISSUE THREAD

**Issue by hzhang1902** [VirtualHotBar/HotPEToolBox#3]
杀毒软件为avira
拦截对象为C:\Users\\***\AppData\Local\Temp\HotPE_TEMP_XZFD\7z\7z.exe
判断为HEUR/apc，malware类型
请问有什么地方需要用到一个迷你7z来解压呢

**Comment by VirtualHotBar** [comment]
资源文件，只有7z的压缩率较高，7z的命令行实现比较简单，如果不压缩程序体积可能达到800mb+

**Comment by VirtualHotBar** [comment]
“C:\Users\***\AppData\Local\Temp\HotPE_TEMP_*\”就是运行时的临时文件夹
