### ISSUE TITLE
HotPE-230730 无法识别到 AX201 网络适配器

### ISSUE THREAD

**Issue by UraraChiya** [VirtualHotBar/HotPEToolBox#31]
当我使用硬盘上的 Windows 时，系统可以正确识别与使用 AX201 网络适配器。但在同一台电脑上，当我从 HotPE-230730.iso 启动时，系统无法识别到 AX201 网络适配器。

**Comment by VirtualHotBar** [comment]
打包网卡驱动模块，https://docs.hotpe.top/course/driver_hpm.html
