### ISSUE TITLE
安装器添加UTF-8支持

### ISSUE THREAD

**Issue by LFWQSP2641** [VirtualHotBar/HotPEToolBox#39]
![image](https://github.com/VirtualHotBar/HotPEToolBox/assets/61956291/5f82d336-7c48-4f2d-80c1-9701c2095892)
![image](https://github.com/VirtualHotBar/HotPEToolBox/assets/61956291/22771bcb-349b-421c-b059-957878400bdb)
如图, 开启UTF-8编码后, 安装失败.

**Comment by VirtualHotBar** [comment]
已实现
