### ISSUE TITLE
识别不到U盘，已解决

### ISSUE THREAD

**Issue by 1604589485** [VirtualHotBar/HotPEToolBox#4]
插入u盘 然后打开软件 软件识别不到u
![无标题](https://user-images.githubusercontent.com/37663618/185747084-4681b5c6-e053-4161-85cf-01978c46e020.png)
盘

**Comment by VirtualHotBar** [comment]
安装工具只支持普通U盘，不支持固态U盘或移动硬盘
如果不识别，可生成ISO文件用第三方工具写入，推荐使用UltraISO、Rufus或Ventoy
