### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by WitherStorm-WS** [VirtualHotBar/HotPEToolBox#46]
我把镜像放**Ventoy**U盘里了，但是打不开，可能是因为硬件不支持Win11吧。
但是ReadMe里说了，“**适用于Win10/11镜像**”。那怎么以Win10模式打开HotPE呢？

**Comment by VirtualHotBar** [comment]
“适用于Win10/11镜像”指此仓库和旧版，新版为单11pe
