### ISSUE TITLE
蓝牙

### ISSUE THREAD

**Issue by ddkwork** [VirtualHotBar/HotPEToolBox#48]
你好，我的是华为平板电脑，物理机上是用蓝牙连接鼠标的，我在hotpe安装到系统启动后安装了蓝牙驱动，但是需要一个启动蓝牙--添加设备，鼠标按下确认连接的过程使得蓝牙鼠标工作，但是我找了半天设置面板，设备管理器，都没看到物理机上的这些菜单，导致鼠标连接不了。您有什么指示吗？谢谢

**Comment by VirtualHotBar** [comment]
HotPE目前不支持蓝牙，可用2.4G的无线键鼠
