### ISSUE TITLE
卸载

### ISSUE THREAD

**Issue by ddkwork** [VirtualHotBar/HotPEToolBox#49]
现在启动菜单多了hotpe，重做系统都有，估计是新建了分区，如何安全的移除hotpe以及它创建的分区呢？移除后分区会自动合并吗？合并安全不？会不会覆盖数据?有没有官方版本的安全卸载方法?

**Comment by VirtualHotBar** [comment]
在HotPE Client点卸载即可。如果没有卸载按钮就点安装，安装后就会出现卸载
![image](https://github.com/VirtualHotBar/HotPEToolBox/assets/96966978/8b62a3e7-d51b-4b7a-b7e0-8de1e0fa7798)

**Comment by ddkwork** [comment]
界面出不来，白窗口



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月1日(周三) 上午9:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [VirtualHotBar/HotPEToolBox] 卸载 (Issue #49)




 
在HotPE Client点卸载即可。如果没有卸载按钮就点安装，安装后就会出现卸载
 image.png (view on web)

**Comment by VirtualHotBar** [comment]
用旧版安装器，安装HotPE，然后在控制面板里卸载

**Comment by VirtualHotBar** [comment]
用这个卸载也可以
[Uninstall.zip](https://github.com/VirtualHotBar/HotPEToolBox/files/15172597/Uninstall.zip)

**Comment by ddkwork** [comment]
这么快吗？合并几个gb的分区，一闪而过，没有提示成功或失败，等下我重启系统看看启动菜单和分区还在不在，稍等哦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月1日(周三) 上午9:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [VirtualHotBar/HotPEToolBox] 卸载 (Issue #49)




 
用这个卸载也可以
 Uninstall.zip

**Comment by ddkwork** [comment]
重启系统发现还在启动菜单啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月1日(周三) 上午9:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [VirtualHotBar/HotPEToolBox] 卸载 (Issue #49)




 
用这个卸载也可以
 Uninstall.zip

**Comment by VirtualHotBar** [comment]
来加Q3143771718，远程我给你删

**Comment by VirtualHotBar** [comment]
这东西跟合并分区有什么关系
