### ISSUE TITLE
安装完成后打开PE无任何反应

### ISSUE THREAD

**Issue by pythonwby** [VirtualHotBar/HotPEToolBox#5]
PE版本是V2.4 Final Build20220812
安装PE时关闭了火绒，并且是在安装文件右键菜单里点击的以管理员身份运行，重启进入PE系统后鼠标键盘没有反应，屏幕上只有壁纸和任务栏，且任务栏上只有win11徽标、一个“X”和时间。

**Comment by pythonwby** [comment]
又试了一次，发现等了几分钟后鼠标和键盘就都能用了，但是7z弹出来一个拒绝访问的报错还另外有一个英文的报错，在桌面上新建文件会提示需要权限，7z管理员身份运行解压文件到桌面也提示拒绝访问，但解压到win11系统里的地方就可以。

**Comment by VirtualHotBar** [comment]
建议带图，硬件兼容性问题无解

**Comment by pythonwby** [comment]
我也觉得是我电脑的问题，因为我电脑除了微PE，其他的PE都打不开

**Comment by pythonwby** [comment]
这是我的配置
![ludashi](https://user-images.githubusercontent.com/67252367/186640296-19a611fc-da31-49e6-90d1-2e7169840e37.jpg)
刚打开PE的时候就是这样
![QQ图片20220825182207](https://user-images.githubusercontent.com/67252367/186640313-289badee-37c7-4227-92cd-775acc76dd03.jpg)
过几分钟后按Alt+Tab就有这两个窗口，必须把第一个窗口关掉才能显示其它的窗口
![QQ图片20220825182213](https://user-images.githubusercontent.com/67252367/186640282-f45f8281-7b73-41c2-9863-e808255c934d.jpg)
关掉那个报错后就是这个7z的报错
![QQ图片20220825182203](https://user-images.githubusercontent.com/67252367/186640305-29b47bef-5f00-47c1-a52a-bb593bb68f2f.jpg)
关掉之后就是这样的
![QQ图片20220825182037](https://user-images.githubusercontent.com/67252367/186640301-bd93fe6c-4dad-4a6f-b05b-cd2c15835e97.jpg)
在这种情况下就可以打开文件资源管理器和开始菜单(其它没试过),开始菜单里左边那一半啥都没有。

**Comment by VirtualHotBar** [comment]
emmm，不知道咋办
