### ISSUE TITLE
建议PE的时间增加注册表设置

### ISSUE THREAD

**Issue by 858622025** [VirtualHotBar/HotPEToolBox#53]
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation]
"RealTimeIsUniversal"=dword:00000001

我是linux windows双系统，windows都增加了上面的注册表，不然时间会乱。现在使用了这个PE，之后再进我的系统，时间就乱掉了。建议默认就加进去这条。另外已经安装好的PE，注册表有办法增加定制项吗？求教程

**Comment by VirtualHotBar** [comment]
可自行用模块解决
